### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by pelon55** [fawno/PHP-Serial#1]
Fatal error: Uncaught Error: Call to undefined function Fawno\PhpSerial\SerialDio()

**Comment by alphp** [comment]
https://github.com/fawno/PHP-Serial#requirements
## Requirements
- PHP Pecl dio extension (>= 0.2.1) for SerialDio

https://pecl.php.net/package/dio
https://windows.php.net/downloads/pecl/releases/dio/0.2.1/
